server:
  port: 4040

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
#          issuer-uri: http://localhost:8080/realms/myrealm

